### ISSUE TITLE
分享貼文時 輸入自己的內容後按提交不會提交輸入的內容

### ISSUE THREAD

**Issue by violetzu** [violetzu/dating-website#1]
分享貼文時，應該還是要能輸入自己想說的內容，但現在輸入後按提交他不會有任何文字

**Comment by Reiner-the-Armor-Titan** [comment]
可以先貼post在資料庫有哪些欄位嗎，它的欄位可能要改一下(現在學校google雲端不能用，看起來也很久沒改了

**Comment by violetzu** [comment]
我把他放到readme最下面

**Comment by violetzu** [comment]
雲端那份文件的需求部分跟資料庫設計我會想把他放到react的rearmed

**Comment by Reiner-the-Armor-Titan** [comment]
post在資料庫要再加一個欄位"shared_post"，用於儲存貼文id並有別於url，但是這樣目前的資料庫大概會炸掉。我Home.jsx還沒完全拆解掉，現在還是用原本的版本，所以先不用改呦

**Comment by violetzu** [comment]
直接存在url會有什麼問題嗎？從urltype判斷是不是有分享貼文就好

**Comment by Reiner-the-Armor-Titan** [comment]
痾就是分享貼文的時候不能貼照片跟YT，我是覺得遲早要改啦，或是決定轉發就是不能貼照片或YT以後就不能改了
欸等一下歐我思考一下還有沒有什麼別的問題

**Comment by violetzu** [comment]
我看到有一個forward.php 這個是不是不需要的

**Comment by Reiner-the-Armor-Titan** [comment]
他好像不在任何component裡，我猜他是"轉送"貼文的意思啦，應該可以刪吧

**Comment by violetzu** [comment]
Postform跟postobject是有什麼區別嗎

**Comment by Reiner-the-Armor-Titan** [comment]
<img width="515" alt="image" src="https://github.com/user-attachments/assets/fa30c2a7-2643-40e3-a232-4374501f0d72">
欸所以shared_post這一項不是在資料庫裡面的嗎

**Comment by violetzu** [comment]
那個應該是就是他查詢完要被分享的貼文之後一起回傳用的吧？就是返回的直接是一個貼文資訊..？

**Comment by violetzu** [comment]
資料庫的架構都在readme了 沒有就沒有

**Comment by violetzu** [comment]
然後我看了我們的前後端，有些請求是有走JSON結構，有些是直接就url參數傳遞進來，看你會不會覺得很亂，很亂的話就都改成json結構也可以

**Comment by Reiner-the-Armor-Titan** [comment]
我有能力的話會的😂

**Comment by violetzu** [comment]
你現在有在改哪裡嗎

**Comment by Reiner-the-Armor-Titan** [comment]
沒有

**Comment by violetzu** [comment]
那post form跟postonject是幹嘛的

**Comment by Reiner-the-Armor-Titan** [comment]
沒有就先拆開來，然後看哪些東西直接放裡面而不是從其他component引入比較好，但是還沒有完成所以沒有加到Home.jsx裡

**Comment by Reiner-the-Armor-Titan** [comment]
因為每個元件頭上的參數(還是property?)有點多，覺得不好閱讀跟參考
我是比較想用物件導向的概念去劃分component啦，如果不好的話就算了

**Comment by violetzu** [comment]
拆拆拆 拆越散越好，可以的話再幫我把顯示貼文跟讀取貼文也拆出來，管理員那邊也要用到貼文的模塊，交給你惹，看可不可以

**Comment by Reiner-the-Armor-Titan** [comment]
我...我盡量！😂

**Comment by Reiner-the-Armor-Titan** [comment]
我嚇傻了這鬼東西比我想像中還難拆😭😭😭
拆到最後好像又不得已變得跟一開始差不多了
果然還是不能在不是物件導向的東西上用物件導向的概念
瘋掉

**Comment by violetzu** [comment]
Push上去了嗎

**Comment by Reiner-the-Armor-Titan** [comment]
還沒 還在調
我可能會把Home()當main()的概念然後把全部東西都塞在這裡
這樣就可以省掉參數一堆跟無法引用的問題
但是就變一大坨

**Comment by Reiner-the-Armor-Titan** [comment]
push 到 by_wu 的分支了

**Comment by violetzu** [comment]
什麼意思？

**Comment by violetzu** [comment]
拆出來不import回去嗎

**Comment by Reiner-the-Armor-Titan** [comment]
就是每個頁面的components可能沒辦法很漂亮的拆成一個一個檔案
1. 如果要從其他檔案(Home.jsx)引入component，就要用一長串property在很多地方重打一次才能引入，這樣有拆根本跟沒拆一樣
2. 不然就是從Home.jsx引入component，但是最後又要import回Home.jsx，整個邏輯流向就變很奇怪

我原本是想把功能可以歸類在一起的東西放在同一個檔案，但是React不是這樣運作的
(很難拆成像C++的標頭檔或函式庫，因為父、子階級的components相互傳遞的東西太多，本來就不好拆成分別的部件
特別是state這個東西在別的檔案裡就無法使用，除非用很迂迴的方式把它在不同檔案中的component間帶來帶去)
所以只好全部放在一起最省力
等我用完再解釋更清楚好了

**Comment by violetzu** [comment]
https://react.dev/reference/react/useContext

**Comment by violetzu** [comment]
算了一坨就一坨吧 好難
