### ISSUE TITLE
just saying

### ISSUE THREAD

**Issue by Reiner-the-Armor-Titan** [violetzu/dating-website#3]
我可能會做一件很可怕的事情，就是把參數名稱改掉and改變元件的參數配置(只是整理一下而已)。
我可能會做可能不會。
希望我不會把東西搞炸掉，雖然我現在是不可能提交變更就是了。

**Comment by violetzu** [comment]
隨便改 怕的話你開以開分支
全部重做也無所謂
該有的功能能正常運行就好

**Comment by violetzu** [comment]
然後我都沒有註解，如果有新東西上去是該註解一下才對

**Comment by violetzu** [comment]
是本來能用結果突然還是不能用還是一開就不能用了？我剛剛看網站是沒問題伺服器應該也正常才對，你不能用的時候網頁能連上https://marimo.idv.tw嗎？

**Comment by Reiner-the-Armor-Titan** [comment]
欸欸欸結果現在又能用了？！？！？！！
我昨天只開過一次，大概就是我傳訊息的時間點開的，然後我開https://marimo.idv.tw/也不能登入我就確定是伺服器問題
(不能運作的意思是指頁面有開出來，但是登入時資料沒有送出，但也沒有錯誤訊息，所以應該是完全沒在動)

**Comment by violetzu** [comment]
頁面有出來就表示網路跟伺服器沒問題，可能那時候剛好資料庫壞了...？有點神奇
可以看一下F12的網路部分看問題出在哪裡

**Comment by Reiner-the-Armor-Titan** [comment]
好我下次爆掉的時候再看看XD

**Comment by Reiner-the-Armor-Titan** [comment]
剛剛catch到的，我是開著的狀態，然後突然php不給抓? 現在又可以了
<img width="457" alt="螢幕擷取畫面 2024-09-11 135358" src="https://github.com/user-attachments/assets/ab6c4aae-a8af-4910-bdce-534fd0b077de">
<img width="300" alt="螢幕擷取畫面 2024-09-11 135404" src="https://github.com/user-attachments/assets/c051d91b-4464-4fc6-9f05-cca18b4508ed">
<img width="960" alt="螢幕擷取畫面 2024-09-11 135409" src="https://github.com/user-attachments/assets/4a54b4c6-8e47-4140-a610-bbce32e50116">

**Comment by violetzu** [comment]
我想看一下網路那頁

**Comment by Reiner-the-Armor-Titan** [comment]
除了網路還有哪些部份要看，現在是好的，它都是突然壞然後不知道下一次突然什麼時候會好

**Comment by violetzu** [comment]
他是寫dns的問題，下次有遇到把個檔案裡的'http://marimo.idv.tw'改成'220.132.170.233'試試看

![image](https://github.com/user-attachments/assets/2ba3e3d1-03ec-466f-b3a4-ded6e68a22b2)

**Comment by violetzu** [comment]
我要開始加新動西跟小修改了，如果你有修改沒問題記得就push上去了
